### ISSUE TITLE
Not every native dependency uses the "ios" folder

### ISSUE THREAD

**Issue by JulianKingman** [Elijen/react-native-fix-headers#2]
Dropping "/ios/" from the pattern will support more node modules, for example https://github.com/terrillo/rn-apple-healthkit/.

It's probably best practice to use the ios folder, but it doesn't mean they all do...

**Comment by Elijen** [comment]
Hi @JulianKingman, sorry for late reply. I think I used `ios` folder specifically because otherwise it took  too long to search through some projects.

I'll take a look if it could be changed.

**Comment by JulianKingman** [comment]
It needs to be run pretty infrequently, so taking a little time shouldn't be a problem. How long was it taking? I created a PR (https://github.com/Elijen/react-native-fix-headers/pull/3), in case you decide to update it. I tried to figure out how to pass a flag that would allow the option, but couldn't figure out how to do that.

**Comment by Elijen** [comment]
@JulianKingman Merged the PR and published a new version into NPM. Thanks and again sorry for the delay!
